services:
  beartrak-search:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Mount a named volume for database persistence
      - beartrak_data:/app/data
    environment:
      - BEARTRAK_ENVIRONMENT=production
      - BEARTRAK_HOST=0.0.0.0
      - BEARTRAK_PRODUCTION_PORT=8080
      - BEARTRAK_DEBUG=false
      - BEARTRAK_PRODUCTION_DB=/app/data/beartrak.db
    restart: unless-stopped

volumes:
  beartrak_data:
    driver: local
