name: Fast CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v4
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync --all-extras --dev
    
    - name: Run quality assurance
      run: make qa
      
    - name: Check code formatting
      run: make format-check

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v4
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync --all-extras --dev
    
    - name: Start server and run integration tests
      run: |
        # Start development server in background (port 8001)
        make start-dev &
        SERVER_PID=$!
        echo "Server PID: $SERVER_PID"
        
        # Wait for server to be ready
        timeout 30 bash -c 'until curl -f http://localhost:8001/health; do sleep 1; done'
        
        # Run integration tests (defaults to port 8001)
        make test-integration
        
        # Cleanup
        kill $SERVER_PID || true
